;Programa que transforma um número decimal
;a binário
COISA: EQU 50
SECTION TEXT
L1: SUB TMP_DATA
S_INPUT OLD_DATA,20
S_OUTPUT OLD_DATA,20
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE COISA
NEW_DATA: SPACE COISA
TMP_DATA: SPACE
