;Programa que transforma um número decimal
;a binário
COISA: EQU 50
SECTION TEXT
L1: SUB TMP_DATA
ADD OLD_DATA+2
COPY OLD_DATA,NEW_DATA
LOAD DOIS
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE COISA
NEW_DATA: SPACE COISA
TMP_DATA: SPACE
